#!/usr/bin/env -S uv run --script --python 3.13
# /// script
# dependencies = [
#   "gnx",
#   "jax[cuda]"
# ]
#
# [tool.uv.sources]
# gnx = { path = "../", editable = true }
#
# ///
# type: ignore

import itertools
from pathlib import Path

import click
import jax
import jax.numpy as jnp
import numpy as np
import rich.progress
from PIL import Image as PILImage

from gnx.datasets import Dataset
from gnx.datasets.image import Image
from gnx.eval.fid import FidStats
from gnx.main.common import setup_logging
from gnx.models.inception import InceptionV3


@click.argument(
    "path_a",
    type=str,
    required=True,
)
@click.argument(
    "path_b",
    type=str,
    required=True,
)
@click.command()
def main(path_a, path_b):
    setup_logging()
    model = InceptionV3.load_fid_pretrained(precision=jax.lax.Precision.HIGHEST)
    stats_a = (
        dataset_stats(model, path_a) if "://" in path_a else path_stats(model, path_a)
    )
    stats_b = (
        dataset_stats(model, path_b) if "://" in path_b else path_stats(model, path_b)
    )
    print(stats_a.distance(stats_b))


def dataset_stats(model, dataset_url) -> FidStats:
    data = Dataset.from_url(dataset_url).splits["train"].batch((64,))
    batches = len(data) // 64
    activations = []
    for batch in rich.progress.track(data.sampler(jax.random.key(42)), total=batches):
        batch = batch.value.pixels
        activations.append(model(batch))
    activations = jnp.concatenate(activations, axis=0)
    return FidStats.from_activations(activations)


def path_stats(model, path) -> FidStats:
    path = Path(path)
    files = list(path.iterdir())
    N = len(files)

    activations = jnp.zeros((N, 2048))
    i = 0

    for batch_files in rich.progress.track(
        itertools.batched(files, 64), total=(N + 63) // 64
    ):
        images = []
        for file in batch_files:
            if file.suffix.lower() in [".jpg", ".jpeg", ".png"]:
                with open(file, "rb") as f:
                    img = PILImage.open(f)
                    img = np.array(img)
                if img.ndim == 2:
                    img = np.expand_dims(img, axis=-1)
                img = img.astype(np.float32) / 255.0
                images.append(2 * img - 1)
        images = Image(np.stack(images))
        images = jax.device_put(images)
        batch_activations = model(images.pixels)
        activations = activations.at[i : i + batch_activations.shape[0]].set(
            batch_activations
        )
        i += batch_activations.shape[0]
    return FidStats.from_activations(activations)


if __name__ == "__main__":
    main()
